services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"  # Adjusted port
    volumes:
      - ./backend:/code
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/dbname
      # - PYTHONPATH=/code
    depends_on:
      - mysql
    command: python3 -m app  # Adjusted to match the module path

  frontend:
    image: nginx:latest
    volumes:
      - ./View:/code/View
      - ./View/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"